# Generated by Django 2.0.1 on 2019-02-23 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('daily', '0004_auto_20180106_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeorder',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='on',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
    ]
