# Generated by Django 2.0.1 on 2018-01-06 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0020_auto_20150910_1407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expenses',
            options={'ordering': ('dateAdded',)},
        ),
    ]
